image: python:3.6-stretch
before_script:
  - apt update -qy
  - apt install -y python3-dev python3-pip python3-wheel libjpeg-dev
  - pip3 install pipenv
  - pipenv --version

test_mapreduce:
  script:
    - cd mapreduce
    - pipenv install --dev --deploy
    - pipenv run pytest --cov
    - pipenv run pylint --disable bad-continuation,arguments-differ,unidiomatic-typecheck *.py
    
test_pig:
  script:
    - cd pig
    - ./fetch_deps.sh
    - pipenv install --dev --deploy
    - pipenv run pytest
