image: ubuntu:xenial
before_script:
  - apt update -qy
  - apt install -y apt-transport-https
  - echo "deb https://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
  - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
  - apt update -qy
  - apt install -y python3-dev python3-pip python3-wheel libjpeg-dev openjdk-8-jdk-headless sbt
  - pip3 install pipenv
  - pipenv --version

variables:
  LC_ALL: "C.UTF-8"
  LANG: "C.UTF-8"

test_python:
  script:
    - cd python
    - pipenv install --dev --deploy
    - pipenv run pytest --cov
    - pipenv run pylint --disable bad-continuation,arguments-differ,unidiomatic-typecheck *.py

test_scalding:
  script:
    - ./please -h
    - cd scalding
    - sbt -mem 1024 test
    - sbt -mem 1024 assembly

# Needs fixing
#test_pig:
#  script:
#    - ./fetch_hadoop.sh
#    - cd pig
#    - pipenv install --dev --deploy
#    - JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:bin/java::") pipenv run pytest
