image: ubuntu:xenial
before_script:
  - apt update -qy
  - apt install -y apt-transport-https software-properties-common
  - add-apt-repository -y ppa:deadsnakes/ppa
  - add-apt-repository -y ppa:cran/poppler
  # kitware (cmake) APT signing key
  - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 6d903995424a83a48d42d53da8e5ef3a02600268
  - apt-add-repository -y 'deb https://apt.kitware.com/ubuntu/ xenial main' 
  # SBT bintray APT signing key
  - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
  - apt-add-repository -y "deb https://dl.bintray.com/sbt/debian /"
  - apt update -qy
  - apt install -y python3-dev python3-pip python3-wheel libjpeg-dev openjdk-8-jdk-headless sbt libpq-dev python-dev python3.8 python3.8-dev python3.8-venv python3.8-distutils pkg-config python3-pytest git libsnappy-dev libsodium-dev libpoppler-cpp-dev cmake libpython3.8-dev
  - python3 -m pip install --upgrade pip
  - python3 -m pip install pipenv
  - pipenv --version

variables:
  LC_ALL: "C.UTF-8"
  LANG: "C.UTF-8"

test_python:
  script:
    - cd python
    - pipenv install --dev --deploy
    - make coverage
    - make lint

test_python_hadoop:
  script:
    - cd python_hadoop
    - pipenv install --dev --deploy
    - pipenv run pytest --cov

# needs fixing; some upstream com.hadoop.gplcompression#hadoop-lzo;0.4.16: java.lang.NullPointerException
# change happened
test_scalding:
  when: manual
  script:
    - ./please -h
    - cd scalding
    - sbt -mem 1024 test
    - sbt -mem 1024 assembly

# Needs fixing
test_pig:
  when: manual
  script:
    - ./fetch_hadoop.sh
    - cd pig
    - pipenv install --dev --deploy
    - JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:bin/java::") pipenv run pytest
